    # https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [2]:
#1. Import numpy as np and see the version

import numpy as np
import sys
print(np.__version__)

1.16.2


In [111]:
#2. How to create a 1D array?

import numpy as np
np.set_printoptions(threshold=4)
num = np.arange(10)
np.set_printoptions(threshold=sys.maxsize)
num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
num = np.arange(15).reshape(3,5)

print(num)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
print(num.ndim)      #----------------->    ndim:-  its returns the number of array dimensions.
print(num.shape)     #----------------->    shape:- its returns the shape of your ndarray as a tuple.
print(num.size)      #----------------->    size:-  Number of elements in the array
print(num.dtype)     #----------------->    dtype:- A dtype is an object describing the type of the elements of an ndarray
print(num.itemsize)  #-----------------> itemsize:- its will return each element bit size

print(type(num))

2
(3, 5)
15
int32
4
<class 'numpy.ndarray'>


In [4]:
list1 = [1,2,3,4,4.5,6.72]
b = np.array( list1 )
print(b)
print(b.dtype)
print(type(b))

[1.   2.   3.   4.   4.5  6.72]
float64
<class 'numpy.ndarray'>


In [5]:
c = np.eye(10, dtype=np.int)
c

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [4]:
#2. How to create a 1D array?

num = np.arange(10)
num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#3. How to create a boolean array?

bool_arr = np.full((3,3),True,dtype=bool)

print(bool_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [15]:
bool_arr = np.full((3,3),1)

print(bool_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
#4. How to extract items that satisfy a given condition from 1D array?
#Q. Extract all odd numbers from arr

arr = np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [8]:
#5. How to replace items that satisfy a condition with another value in numpy array?
#Q. Replace all odd numbers in arr with -1

arr = np.arange(10)
print(arr)
arr[arr%2==1]=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [10]:
#6. How to replace items that satisfy a condition without affecting the original array?
#Q. Replace all odd numbers in arr with -1 without changing arr

arr = np.arange(10)
arr2=(arr).copy()
arr2[arr%2==1] = -1
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [18]:
#6. How to replace items that satisfy a condition without affecting the original array?
#Q. Replace all odd numbers in arr with -1 without changing arr

arr = np.arange(10)
arr2 = np.where(arr % 2 == 1, -1, arr)

print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [61]:
arr = np.arange(10)

arr2_ind = np.where(arr % 2 == 1)


#print(arr2_ind)
arr.take(arr2_ind)

array([[1, 3, 5, 7, 9]])

In [16]:
#7. How to reshape an array?
#Q. Convert a 1D array to a 2D array with 2 rows

arr = np.arange(10)
print(arr)
arr.reshape(2,-1)
#print(arr)


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
#8. How to stack two arrays vertically?
#Q. Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print("Row wise")
print(np.concatenate([a, b], axis=0))
print(np.vstack([a,b]))
print(np.r_[a,b])


Row wise
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [24]:
#9. How to stack two arrays horizontally?
#Q. Stack arrays a and b horizontally

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


print("Col wise")
print(np.concatenate([a, b], axis=1))
print(np.hstack([a,b]))
print(np.c_[a,b])

Col wise
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [53]:
print(np.arange(10, 0, -2))  

[10  8  6  4  2]


In [29]:
#10. How to generate custom sequences in numpy without hardcoding?
# desired output [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
a = np.array([1,2,3])
print(np.repeat(a,3))
print(np.tile(a,3))
np.concatenate([np.repeat(a,3),np.tile(a,3)])

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
#11. How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,9,4,9,8,5])

np.intersect1d(a,b)



array([2, 4, 5])

In [89]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)
a[(a>=5) & (a<=10)]


array([5, 6])

In [33]:
#12. How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [38]:
#13. How to get the positions where elements of two arrays match?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# Output - (array([1, 3, 5, 7]),)

print("Common elements: ", np.intersect1d(a,b))
print(np.where(a==b))

Common elements:  [2 4]
(array([1, 3, 5, 7], dtype=int64),)


In [44]:
#14. How to extract all numbers between a given range from a numpy array?

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.where((a>=5) & (a<10))]
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [91]:
#Q. Convert the function maxx that works on two scalars, to work on two arrays.

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    


pair_max = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [45]:
#16. How to swap two columns in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, [0,2,1]])
"""
print(arr[ [0,2,1],:])
print(arr[::-1])
print(arr[:,::-1])
"""

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


'\nprint(arr[ [0,2,1],:])\nprint(arr[::-1])\nprint(arr[:,::-1])\n'

In [46]:
#17. How to swap two rows in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[ [0,2,1],:])

"""

print(arr[::-1])
print(arr[:,::-1])
"""

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [6 7 8]
 [3 4 5]]


'\n\nprint(arr[::-1])\nprint(arr[:,::-1])\n'

In [47]:
#18. How to reverse the rows of a 2D array?

arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[::-1])

"""


print(arr[:,::-1])
"""

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


'\n\n\nprint(arr[:,::-1])\n'

In [49]:
#19. How to reverse the columns of a 2D array?

arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [56]:
#20. How to create a 2D array containing random floats between 5 and 10?

arr = np.random.randint(5,10, size=(5,3))
print(arr)
arr = np.random.uniform(5,10, size=(5,3))
print(arr)

[[8 5 9]
 [8 7 5]
 [8 7 5]
 [5 7 8]
 [9 7 7]]
[[5.68450723 6.96129181 9.02288555]
 [5.33296308 7.47562506 7.69702197]
 [8.87782861 8.4500472  7.69861789]
 [7.37974315 7.83357629 6.88952298]
 [7.14319837 7.35057278 6.42441395]]


In [58]:
#21. How to print only 3 decimal places in python numpy array?

arr = np.random.uniform(5,10, size=(5,3))
np.set_printoptions(precision=3)
print(arr)

[[5.38  8.786 6.85 ]
 [9.963 7.268 5.188]
 [9.241 5.276 7.09 ]
 [6.382 8.239 8.524]
 [6.233 6.11  7.076]]


In [61]:
#22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
rand_arr

np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [67]:
#23. How to limit the number of items printed in output of numpy array?
a = np.arange(15)
a
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2,  3,  4,  5, ...,  9, 10, 11, 12, 13, 14])

In [70]:
#24. How to print the full numpy array without truncating?
import sys
a = np.arange(15)
a
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
#25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

#url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=float)
#iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3]


array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan]])

In [89]:
#26. How to extract a particular column from 1D array of tuples?

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
#iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:3,4:5])

#iris[:5,['species']]


[[b'Iris-setosa']
 [b'Iris-setosa']
 [b'Iris-setosa']]


In [98]:
#27. How to convert a 1d array of tuples to a 2d numpy array?

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None,usecols=[0,1,2,3])
#iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:3,])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [105]:
#27. How to convert a 1d array of tuples to a 2d numpy array?

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None)
#iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris_upd = np.array([row.tolist()[:4] for row in iris])
iris_upd

C:\Users\Deepak Sadanandan\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [109]:
#28. How to compute the mean, median, standard deviation of a numpy array?

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0])
#iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
mea, med, std = np.mean(iris),np.median(iris),np.std(iris)
print(mea, med, std)

5.843333333333334 5.8 0.8253012917851409


In [ ]:
#29. How to normalize an array so the values range exactly between 0 and 1?

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0])

#???

In [ ]:
#30. How to compute the softmax score?

#Q. Compute the softmax score of sepallength.

#???

In [115]:
#31. How to find the percentile scores of a numpy array?

#Q. Find the 5th and 95th percentile of iris's sepallength

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0])

np.percentile(iris, q=[5, 95])

array([4.6  , 7.255])

In [123]:
#32. How to insert values at random positions in an array?

#Q. Insert np.nan values at 20 random positions in iris_2d dataset

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

i,j = np.where(iris) #rows and columns

np.random.seed(100)
#iris[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris)


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' nan b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' nan b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' nan b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' nan b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Iris-setosa']


In [9]:
#33. How to find the position of missing values in numpy array?

#Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
#iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])
#iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0])
iris[np.random.randint(150, size=20)] = np.nan


np.isnan(iris[:]).sum()
np.isnan(iris[:])
print(np.where(np.isnan(iris[:])))
iris


(array([ 14,  18,  19,  29,  34,  36,  63,  69,  73,  81,  84,  91,  96,
       117, 123, 134, 143], dtype=int64),)


array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, nan, 5.7, 5.4, 5.1, nan, nan, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, nan, 4.8, 5.4, 5.2, 5.5, nan, 5. , nan, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , nan, 5.6,
       6.7, 5.6, 5.8, 6.2, nan, 5.9, 6.1, 6.3, nan, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, nan, 5.8, 6. , nan, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       nan, 5.8, 5. , 5.6, 5.7, nan, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       nan, 7.7, 6. , 6.9, 5.6, 7.7, nan, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, nan, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       nan, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [22]:
#34. How to filter a numpy array based on two or more conditions?

#Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 
# and sepallength (1st column) < 5.0

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])

#print(iris[:10])

#iris[np.where((iris[:,0]<5))]
iris[np.where((iris[:,2]>1.5)&(iris[:,0]<5))]

#iris


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [4]:
#35. How to drop rows that contain a missing value from a numpy array?

#Q. Select the rows of iris_2d that does not have any nan value

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


#print(np.array (np.where((iris[:]))) ) # this gives all the index
#print(np.array(np.where(np.isnan(iris[:])))) # this gives the index of all the nan

iris[np.setdiff1d((np.array(np.where(iris[:]))),(np.array(np.where(np.isnan(iris[:])))))]





array([], shape=(0, 4), dtype=float64)

In [9]:
#36.How to find the correlation between two columns of a numpy array?

#Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])

print(iris[:5])
print(iris[:5, 0])
print(iris[:5, 2])

np.cov(iris[:, 0], iris[:, 2])
np.corrcoef(iris[:, 0], iris[:, 2])[0,1]




[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[5.1 4.9 4.7 4.6 5. ]
[1.4 1.4 1.3 1.5 1.4]


0.8717541573048718

In [11]:
#37. How to find if a given array has any null values?

#Q. Find out if iris_2d has any missing values.
url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

np.isnan(iris).any()

True

In [15]:
#38. How to replace all missing values with 0 in a numpy array?

#Q. Replace all ccurrences of nan with 0 in numpy array
url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0,1,2,3])
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print(iris[15:20])
iris[np.isnan(iris)] = 0
iris[15:20]

[[5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [nan 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


array([[5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [0. , 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3]])

In [17]:
#39. How to find the count of unique values in a numpy array?

#Q. Find the unique values and the count of unique values in iris's species

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

np.unique(iris[:,4], return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([50, 50, 50], dtype=int64))

In [20]:
#40. How to convert a numeric to a categorical (text) array?

#Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
#Less than 3 --> 'small'
#3-5 --> 'medium'
#'>=5 --> 'large'

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#np.digitize(iris[:, 2].astype('float'), [0, 3, 6, 10])

label = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label[x] for x in np.digitize(iris[:, 2].astype('float'), [0, 1, 3, 10])]
petal_length_cat[:5]

['medium', 'medium', 'medium', 'medium', 'medium']

In [26]:
#41. How to create a new column from existing columns of a numpy array?
#Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sepallength = iris[:, 0].astype('float')
petallength = iris[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

print(volume.ndim) 
print(volume.shape) 
print(volume.size) 

out = np.hstack([iris, volume[:, np.newaxis]])
out[:5]




1
(150,)
150


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        36.65191429188092]], dtype=object)

In [28]:
#42. How to do probabilistic sampling in numpy?
#Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica

url = 'C:/Users/Deepak Sadanandan/Desktop/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sepallength = iris[:, 0].astype('float')
petallength = iris[:, 2].astype('float')
species = iris[:, 4].astype('str')

out = np.hstack([iris, volume[:, np.newaxis]])
out[:5]




1
(150,)
150


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        36.65191429188092]], dtype=object)